language: node_js
node_js:
  - 6
  - 8
  - 10

env:
  global:
    - secure: "caR4aYAoUylS0d7a14zDXkxV9g2LnQAOufdm3JwyDiPUVCC2GWVf42FvovK3wTynJDPtskX175bqVr4u9smHj/y0wz0XrGUkfYBeMkff57Xd2zFJ+kUR6nqB3xqaqMCffqJNflij0eT+TMgfBe8gBc+q9Fs6PB5rGKwuIkv9+/L1toebrWJJE2Uj53fROekhTtR8oeWECun3dxgtczOpV/vueJUmgC0mfavEYJdhAuNZxNByjsZHvfct3lMmsPJOXjWKRbnNYO9rgrJwwJfVkbv86Qg8tieuOD0H+eUbeeBIyQUIriNeCx/STe0frvraWX4jIoZ66BIW6kmqfUxPfXvuIBVKdBd//jWnW7g58DquH5MTIaSgQh4plzuuFoCqli7Kv4GCzgfCAYdRpvwsbA+rJ5wpAHEitmerN/6PQa2+UBCTilkHqd/y+Dm0y8fNnocFXDmGVa5H/NtsxT04OtorsFIXCn2mQALdPYOA6575keKTH1E7YWr26jauK38Et15y52eF9ALPNG8nQ/y1WOPa9kJdux7qNJED+Wy6OEnXrPsfiaALDNWF/gumc4/ePhU4dyUdF6kFcCJWc3HKsOy2XGUMmwtFhJBVvy/p9hgYlY2nD7d2ILavGwPK8Bp3lebBqdLQLMVw7eQZO6tYfqms+2uYkbDzh9sdUP/zPGA="
    - secure: "EpnrG4kILTTPKJptf10UAr4X56oM3I0hAVsuOjxApMTv74CEuqbmkf65U5Ei/olqGJ/c2K/DOg8HPGT+SQyLG9J5yw4Pt8Mx7VmuFjiXgFXLEeUljfiX1+UGluJnT9IpOsMR30gyXQeMxnaxn7ijQoeSlaSDxJqGMLW8JjUXnf2Wa98xkqcsQDdFCVHx4g6A//ZZzbmd1B7v/II2PJb+ftS2YlI/qDKYd4ic1O1yllJczjmlx8xdcqWMtbvdZ3NLBblWGrp+tBcZq9/wqLTq7AnpVpXXZB0tZOlV8r1kqPpyYF5v8Fjx/qALcnQ1ix3VrX2cEP5xDkygK7Am8Y6G/1Fo7IQkpnkKbRRtZDxOmaj5TYFPAuIqSUKT/2ncd9UkUizeQrA4rzVi+Gn+vU5n1+4oIO634Kaa4IpFmn1t08tOe4duAqycsm450bLO1hCBh//8dVmKTP4SsmPz5CN78yP/ot+fs6RQ0yJzVDfFSr4gkMmJdwWtiufAqvnlCf6wVkdy21m65aJUCYPfu2uDPLN7XKSMDOCrRUFp7WiqldwLH3yOpq7LVJ83C8gRr48KUK6rHqjDBkRki2W2M5I/mzs60bGtt6F5wvN+0FMuovRno3AbLykMnvbhjijHgc3vDwrP2NsFjwS4T6mG1AX8icCLNmbBm762I5nNcOj39JQ="

script:
  - travis_retry npm test
